### ISSUE TITLE
`readonlyRootFilesystem` should be `false` (or, should not be configured) in task definition to use ECS Exec

### ISSUE THREAD

**Issue by toricls** [aws-containers/amazon-ecs-exec-checker#21]
The managed agent (= SSM agent) requires to create directories and files as described in [this proposal](https://github.com/aws/containers-roadmap/issues/1050).

See the details about `readonlyRootFilesystem` in [the ECS official documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_storage).

This check should be implemented as a red item.

**Comment by WhyNotHugo** [comment]
Does this imply that ExecuteCommand only works if the filesystem is _not_ mounted readonly?

Will this never be supported in future? This is a hard dealbreaker for me, since I cannot downgrade security in my production cluster and make the root read-write.

Might it be possible to mount a `tmpfs` in the right place as a workaround?

**Comment by toricls** [comment]
Hi @WhyNotHugo, thanks for the comment! As you pointed out ECS Exec requires the container storage writable at this moment. I also suggested the team to explicitly mention on this in the ECS official documentation but it'll take some time I think.

Regarding workaround, I need to do some additional tests to comment on it but I think I can think of some ways to deal with. I will note that in the README or somewhere in this repository once we implemented this check.

**Comment by toricls** [comment]
Dropping an update - we're going to clarify in the ECS doc with https://github.com/awsdocs/amazon-ecs-developer-guide/pull/157 that ECS Exec doesn't support read-only containers at this moment. This change will be included in the next batch of the ECS doc release.

**Comment by sd65** [comment]
@toricls I've managed to get it working with `readonlyRootFilesystem: true` by mounting the `/managed-agents`, `/var/lib/amazon/ssm` and `/var/log/amazon/ssm` as writable volumes inside. Works fine for me.

But there is still one undocumented limitation : some [Linux capabilities](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-kernelcapabilities.html) are needed and it's too hard/slow to reverse engineer this... If you got any info on this, it would be highly appreciated !

**Comment by toricls** [comment]
@sd65 Thanks for the info!

Actually I was thinking very similar approach to make it work in read-only containers. There were two ways in my mind, by making those directories writable by 1) creating them in `Dockerfile`, or 2) creating them in ECS task definition using bind mount.

It's reasonable to me that the ssm-agent requires some of the [default allowed linux caps](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities). I assume you took one of the workarounds I described above with dropping some linux caps from your containers, but could you possibly elaborate more on your approach?

**Comment by L1Cafe** [comment]
@toricls I was talking to @sd65 in our correspondence. I was ready to open a new issue for the Linux capabilities situation on behalf of them on https://github.com/aws/containers-roadmap, do you want me to?

Also: Should I open an issue on https://github.com/aws/containers-roadmap in regards to this readonly matter? Hopefully we can either update the documentation or the way ECS Exec works.

Let me know your thoughts (reach me on Slack "Leon Castillejos" for more details).

**Comment by sd65** [comment]
@toricls You're completely right, the default allowed Linux capabilities are enough for the ECS exec agent to work. We have a drop all caps then whitelist approach on our containers, so I guess I will have to remove them one by one and see if it's still working :stuck_out_tongue: 

@L1Cafe Glad to see you here, hope we can update the documentation soon to prevent more headaches.

**Comment by toricls** [comment]
@sd65 I would appreciate if you could create feature requests with your use cases in our [containers roadmap repository](https://github.com/aws/containers-roadmap/issues) as a user.
I think the requests will be two items:

**1.ECS Exec feature request - Support `readonlyRootFilesystem` containers**

This would be a feature request since we, the ECS team doesn't officially support read-only containers as described in the documentation [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html#ecs-exec-considerations) at this moment.

**2.ECS Exex documentation request - Document on required Linux caps**

This would be a doc update request to explicitly state the required Linux caps for ECS Exec on the ECS official doc or on the SSM agent doc.

**Comment by toricls** [comment]
Thank you @sd65!

**Comment by toricls** [comment]
Write a small article for working around this limitation - https://toris.io/2021/06/using-ecs-exec-with-readonlyrootfilesystem-enabled-containers/
