### ISSUE TITLE
Support for Profile?

### ISSUE THREAD

**Issue by deleugpn** [aws-containers/amazon-ecs-exec-checker#26]
While trying to use the tool, I get an error that suggests that I use `aws configure`. However I have several accounts/credentials and none of them are default to my environment. Using profile would be ideal.

**Comment by toricls** [comment]
Hi, thanks for creating this issue @deleugpn!

I think you can use your profile by just exposing it as `AWS_PROFILE` like:

```
AWS_PROFILE=<your profile name> ./check-ecs-exec.sh <your cluster name> <your task id>
```

**Comment by toricls** [comment]
Also, feel free to reopen the issue if my comment above is not getting your point!

**Comment by deleugpn** [comment]
`AWS_PROFILE` works, thanks!
